# Generated by Django 5.0.7 on 2024-07-18 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Department',
            new_name='car_model',
        ),
    ]
