# Generated by Django 5.0.7 on 2024-07-18 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_department_car_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cus_contact',
            field=models.IntegerField(null=True),
        ),
    ]
