# Generated by Django 5.0.7 on 2024-07-18 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_customer_cus_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='car_model',
            name='car_color',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
